### ISSUE TITLE
bilibili在开启wayland后打不开

### ISSUE THREAD

**Issue by Love-in-idleness** [madoka773/flatpak#53]
我尝试使用 bilibili-flags.conf 开启 wayland 后出现了类似 https://github.com/msojocs/bilibili-linux/issues/118 中的问题。而我在机器上使用 bilbili 的 appimage 版本，开启 wayland 后并没有此问题。目前来看应该是 flatpak 打包的问题，希望修复。

**Comment by pugaizai** [comment]
fixed on https://github.com/pugaizai/flatpak/commit/142bceaf9fe215f39eee6241aeccd0f78a7b926b

**Comment by pugaizai** [comment]
更新后你需要用flatseal之类的工具手动打开wayland支持

**Comment by pugaizai** [comment]
讲道理对于electron21我是不建议用wayland的

**Comment by pugaizai** [comment]
另外本flatpak并不支持用xxx-flags.conf
